### ISSUE TITLE
[Question] Run viewer on private ip than local host

### ISSUE THREAD

**Issue by coolkite** [gsgen3d/gsgen#12]
Hi,

i am having an issue with viewing my rendering of the prompt using the viewer script when I run it on my server. Since I cannot access the localhost link through my server's console, I forward it using ngrok and view it on my local machine (macbook pro). However, the checkpoint doesn't render. As such, I am wondering if there is a way to run the viewer on a private ip than localhost.

<img width="1440" alt="Screenshot 2023-10-10 at 4 23 43 PM" src="https://github.com/gsgen3d/gsgen/assets/45459835/40c57a85-4532-49f1-aae2-99891cf03306">

I am able to look at the gifs used for eval in the wandb folder so I know the model trained properly but there seems to be some issue with the viewing. 

If using the splat viewer is a better option, how and what do I upload to view it in the browser?

**Comment by heheyas** [comment]
Hi coolkite,

Thank you for your interest. In my practical usage, I will use [SSH for port tunneling](https://www.ssh.com/academy/ssh/tunneling-example).
```bash
ssh -L <YOUR_LOCAL_PORT>:<YOUR_SERVER_IP>:<YOUR_SERVER_PORT> <YOUR_USER>@<YOUR_SERVER>
```
where the `<YOUR_SERVER_PORT>` is `8080` by default.

If you wish to use the splat viewer, first convert the `.pt` checkpoint to `.ply` file by using the scripts:
```bash
python utils/export.py <your_ckpt> --type ply
```
where the `<your_ckpt>` can be the path to the `.pt` checkpoint file or, more conveniently, can be the id for the run (the display name of the run in wandb, e.g. `0|213630|2023-10-11|a_high_quality_photo_of_a_corgi`).
After running this command, you can find the exported `.ply` file in the `exports/ply` directory.
Then, open [the online splat viewer](https://gsgen3d.github.io/viewer.html) and drag the `.ply` file into the browser window. 

I am really sorry for the inconvenience caused by the design and the incomplete documentation. Feel free to ask any questions about the viewer and our method.

Best regards,
heheyas
