### ISSUE TITLE
[Question] Reproduction problem about Compactness-based Densification

### ISSUE THREAD

**Issue by haodong2000** [gsgen3d/gsgen#9]
Dear authors, thanks for your great work, but I met problems while training with the Compactness-based Densification proposed in section 4.2 of your paper, like the figure below:

![image](https://github.com/gsgen3d/gsgen/assets/67775090/8e78f908-10b8-40e0-a133-0ffd811bb00f)

I found that in your `conf/base.yaml`:

```
renderer:
  ...
  densify:
    enabled: true
    type: official
    ...
    use_legacy: true
```

, which means that in function `def densify()` at `gs/gaussian_splatting.py`:

```python
    def densify(self, step, verbose=True):
        # check if densify is enabled and triggered, if true, do densify
        if not self.densify_cfg.enabled:
            return
        if step < self.densify_cfg.warm_up or step > self.densify_cfg.end:
            return

        if step_check(step, self.densify_cfg.period, True):
            if self.densify_cfg.use_legacy:
                self.densify_legacy(step, verbose)
                if "compatness" in self.densify_cfg.type:
                    self.densify_by_compatness(K=self.densify_cfg.get("K", 3))
```

, the function `self.densify_by_compatness()` will not be executed and only `self.densify_legacy()` will be ran.

And then I set `renderer.densify.type="compatness"`, to run it, but the proformance is not quite good with prompt _"a zoomed out photo of a 3D model of an adorable cottage with a thatched roof"_ with initial prompt _"a cottage"_, at iter7000 (because after including the `self.densify_by_compatness()`, the training stopped at iter7000)

- with compatness
![house_with_compatness_iter7000](https://github.com/gsgen3d/gsgen/assets/67775090/33f29290-e5d5-44f8-ab5c-cdeff2c496f2)

- without compatness
![house_without_compatness_iter7000](https://github.com/gsgen3d/gsgen/assets/67775090/4105f074-ee4b-4825-a0b8-3f2fc33c505a)

There might be several reasons, the first that I came up with that  in defalult, the pruning operation is disabled in config. I will report the result after adding the pruning. 

But the most important is authors' explaination, cause you are the most familiar with the code. Could you kindly provide some advice, since we are also doing Text-to-3D tasks, and the Compactness-based Densification really attracting us.

Thanks! 😄

**Comment by heheyas** [comment]
Hi haodong,

Thanks for your interest. If you find the model contains an excessively large number of Gaussians, please set a smaller K by `+renderer.densify.K=1` or a larger period on densification by `renderer.densify.period=2000` which works fine in my case. Some of the configs have not been released yet since we want to do better (including guidance with [DeepFloyd IF](https://www.deepfloyd.ai/deepfloyd-if) and VSD loss in [ProlificDreamer](https://github.com/thu-ml/prolificdreamer)).

The error that happened in the pruning is caused by the `alpha_thresh: 1000` since `alpha_thresh` refers to the minimal opacity value thus all of the Gaussians are pruned. You can set the `alpha_thresh=0.05` to enable a correct prune. Sorry for not making it clear in the readme. We are still working on GSGEN. If you have any more questions about the approach, feel free to [email me](mailto:chenzl22@mails.tsinghua.edu.cn).

**Comment by haodong2000** [comment]
Many thanks for your explaination! And sorry I did not set params like `alpha_thresh` and `radii2d_thresh` carefully :smile:

After adding the Compactness-based Densification, the details seems to be better!

- with compactness
![house_with_compatness](https://github.com/gsgen3d/gsgen/assets/67775090/cbf5deb1-fe3c-42bc-ba75-a724836bc638)

- without compactness
![house_without_compatness](https://github.com/gsgen3d/gsgen/assets/67775090/a3263c5f-9df3-452c-b340-4883d91a601e)

I am also trying to add the pruning at the same time, thanks again!
